version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - sportsstore-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - backend  # Ensures backend starts first
    networks:
      - sportsstore-network

networks:
  sportsstore-network:
    driver: bridge
